[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ovos-skill-ip"
dynamic = ["version"]
description = "OVOS IP address skill"
readme = "README.md"
license = {text = "Apache-2.0"}
authors = [
    {name = "JarbasAi", email = "jarbasai@mailfence.com"}
]
keywords = ["ovos", "skill", "plugin"]
dependencies = [
    "ifaddr",
    "ovos-workshop>=0.0.12,<10.0.0"
]

[project.optional-dependencies]
test = [
    "ovoscope>=1.5.0,<2.0.0",
    "ovos-adapt-parser>=1.3.3a1",
    "pytest>=7.0.0,<9",
    "pytest-timeout>=2.0.0"
]

[project.urls]
Homepage = "https://github.com/OpenVoiceOS/ovos-skill-ip"

[project.entry-points."ovos.plugin.skill"]
"ovos-skill-ip.openvoiceos" = "ovos_skill_ip:IPSkill"

[tool.setuptools]
packages = ["ovos_skill_ip"]

[tool.setuptools.package-dir]
ovos_skill_ip = ""

[tool.setuptools.dynamic]
version = {attr = "ovos_skill_ip.version.__version__"}

[tool.setuptools.package-data]
ovos_skill_ip = [
    "*.json",
    "locale/**/*",
    "locale/*/*.voc",
    "locale/*/*.intent",
    "locale/*/*.dialog",
]
